config/routes.rb
Prospera2::Application.routes.draw do
  

  resources :aglayouts

  resources :lookup_table_precios

  resources :plans

  resources :layouts
  resources :temp_layouts
   get 'gracias' => 'home#thankyou'
   get 'palig' => 'home#palig'
   get 'bupa' => 'home#bupa'
   get 'gastosmedicos' => 'home#gastosmedicos'
   get 'cotizacionpalig' => 'home#cotizacionpalig'
   get 'agentes' => 'home#agentes'

  root :to => 'home#index'

end

app/models/aglayout.rb
class Aglayout < ActiveRecord::Base
  attr_accessible :nombre, :celular, :email, :estadoderesidencia,  :edadetitular, :edaddeconyugue, :numdehijosconedadde24ymenores, :formadepago, :edaddehijo1mayora24, :edaddehijo2mayora24, :edaddehijo3mayora24, :edaddehijo4mayora24, :edaddelpadredeltitular, :edaddelamadredeltitular, :edaddelasuegradeltitular, :edaddelasuegrodeltitular, :plan, :viajes, :cashemergencia
before_create :set_plan

private
	def set_plan
		if self.viajes == '4 o más'
			self.plan = 'WA'
		else
			self.plan = 'PA'
		end
		
	end
    
end

app/controllers/aglayouts_controller.rb
class AglayoutsController < ApplicationController
  # GET /aglayouts
  # GET /aglayouts.json
  
  def create
    @aglayout = Aglayout.new(params[:aglayout])

    respond_to do |format|
      if @aglayout.save
        format.html { redirect_to gracias_path, notice: 'Aglayout was successfully created.' }
        format.json { render json: @aglayout, status: :created, location: @aglayout }
      else
        format.html { render action: "new" }
        format.json { render json: @aglayout.errors, status: :unprocessable_entity }
      end
    end
  end

 
end

app/helpers/aglayouts_helper.rb
module AglayoutsHelper
end

app/views/aglayouts/_form.html.erb
<%= form_for(@aglayout) do |f| %>
  <% if @aglayout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aglayout.errors.count, "error") %> prohibited this aglayout from being saved:</h2>

      <ul>
      <% @aglayout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aglayouts/edit.html.erb
<h1>Editing aglayout</h1>

<%= render 'form' %>

<%= link_to 'Show', @aglayout %> |
<%= link_to 'Back', aglayouts_path %>

app/views/aglayouts/index.html.erb
<h1>Listing aglayouts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @aglayouts.each do |aglayout| %>
  <tr>
    <td><%= link_to 'Show', aglayout %></td>
    <td><%= link_to 'Edit', edit_aglayout_path(aglayout) %></td>
    <td><%= link_to 'Destroy', aglayout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Aglayout', new_aglayout_path %>

app/views/aglayouts/new.html.erb
<h1>New aglayout</h1>

<%= render 'form' %>

<%= link_to 'Back', aglayouts_path %>

app/views/aglayouts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_aglayout_path(@aglayout) %> |
<%= link_to 'Back', aglayouts_path %>