config/routes.rb
Prospera2::Application.routes.draw do
  

  resources :aglayouts

  resources :lookup_table_precios

  resources :plans

  resources :layouts
  resources :temp_layouts
   get 'gracias' => 'home#thankyou'
   get 'palig' => 'home#palig'
   get 'bupa' => 'home#bupa'
   get 'gastosmedicos' => 'home#gastosmedicos'
   get 'cotizacionpalig' => 'home#cotizacionpalig'
   get 'agentes' => 'home#agentes'

  root :to => 'home#index'

end

app/models/lookup_table_precio.rb
class LookupTablePrecio < ActiveRecord::Base
  attr_accessible :edad, :llave, :pan_mx_i, :pan_mx_ii, :pan_mx_iii, :pan_mx_iv, :pan_mx_v, :producto, :zona
end

app/controllers/lookup_table_precios_controller.rb
class LookupTablePreciosController < ApplicationController
  # GET /lookup_table_precios
  # GET /lookup_table_precios.json
  def index
    @lookup_table_precios = LookupTablePrecio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lookup_table_precios }
    end
  end

  # GET /lookup_table_precios/1
  # GET /lookup_table_precios/1.json
  def show
    @lookup_table_precio = LookupTablePrecio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lookup_table_precio }
    end
  end

  # GET /lookup_table_precios/new
  # GET /lookup_table_precios/new.json
  def new
    @lookup_table_precio = LookupTablePrecio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lookup_table_precio }
    end
  end

  # GET /lookup_table_precios/1/edit
  def edit
    @lookup_table_precio = LookupTablePrecio.find(params[:id])
  end

  # POST /lookup_table_precios
  # POST /lookup_table_precios.json
  def create
    @lookup_table_precio = LookupTablePrecio.new(params[:lookup_table_precio])

    respond_to do |format|
      if @lookup_table_precio.save
        format.html { redirect_to @lookup_table_precio, notice: 'Lookup table precio was successfully created.' }
        format.json { render json: @lookup_table_precio, status: :created, location: @lookup_table_precio }
      else
        format.html { render action: "new" }
        format.json { render json: @lookup_table_precio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lookup_table_precios/1
  # PUT /lookup_table_precios/1.json
  def update
    @lookup_table_precio = LookupTablePrecio.find(params[:id])

    respond_to do |format|
      if @lookup_table_precio.update_attributes(params[:lookup_table_precio])
        format.html { redirect_to @lookup_table_precio, notice: 'Lookup table precio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lookup_table_precio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lookup_table_precios/1
  # DELETE /lookup_table_precios/1.json
  def destroy
    @lookup_table_precio = LookupTablePrecio.find(params[:id])
    @lookup_table_precio.destroy

    respond_to do |format|
      format.html { redirect_to lookup_table_precios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lookup_table_precios_helper.rb
module LookupTablePreciosHelper
end

app/views/lookup_table_precios/_form.html.erb
<%= form_for(@lookup_table_precio) do |f| %>
  <% if @lookup_table_precio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lookup_table_precio.errors.count, "error") %> prohibited this lookup_table_precio from being saved:</h2>

      <ul>
      <% @lookup_table_precio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :producto %><br />
    <%= f.text_field :producto %>
  </div>
  <div class="field">
    <%= f.label :zona %><br />
    <%= f.number_field :zona %>
  </div>
  <div class="field">
    <%= f.label :edad %><br />
    <%= f.number_field :edad %>
  </div>
  <div class="field">
    <%= f.label :llave %><br />
    <%= f.text_field :llave %>
  </div>
  <div class="field">
    <%= f.label :pan_mx_i %><br />
    <%= f.text_field :pan_mx_i %>
  </div>
  <div class="field">
    <%= f.label :pan_mx_ii %><br />
    <%= f.text_field :pan_mx_ii %>
  </div>
  <div class="field">
    <%= f.label :pan_mx_iii %><br />
    <%= f.text_field :pan_mx_iii %>
  </div>
  <div class="field">
    <%= f.label :pan_mx_iv %><br />
    <%= f.text_field :pan_mx_iv %>
  </div>
  <div class="field">
    <%= f.label :pan_mx_v %><br />
    <%= f.text_field :pan_mx_v %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lookup_table_precios/edit.html.erb
<h1>Editing lookup_table_precio</h1>

<%= render 'form' %>

<%= link_to 'Show', @lookup_table_precio %> |
<%= link_to 'Back', lookup_table_precios_path %>

app/views/lookup_table_precios/index.html.erb
<h1>Listing lookup_table_precios</h1>

<table>
  <tr>
    <th>Producto</th>
    <th>Zona</th>
    <th>Edad</th>
    <th>Llave</th>
    <th>Pan_mx_i</th>
    <th>Pan_mx_ii</th>
    <th>Pan_mx_iii</th>
    <th>Pan_mx_iv</th>
    <th>Pan_mx_v</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lookup_table_precios.each do |lookup_table_precio| %>
  <tr>
    <td><%= lookup_table_precio.producto %></td>
    <td><%= lookup_table_precio.zona %></td>
    <td><%= lookup_table_precio.edad %></td>
    <td><%= lookup_table_precio.llave %></td>
    <td><%= lookup_table_precio.pan_mx_i %></td>
    <td><%= lookup_table_precio.pan_mx_ii %></td>
    <td><%= lookup_table_precio.pan_mx_iii %></td>
    <td><%= lookup_table_precio.pan_mx_iv %></td>
    <td><%= lookup_table_precio.pan_mx_v %></td>
    <td><%= link_to 'Show', lookup_table_precio %></td>
    <td><%= link_to 'Edit', edit_lookup_table_precio_path(lookup_table_precio) %></td>
    <td><%= link_to 'Destroy', lookup_table_precio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lookup table precio', new_lookup_table_precio_path %>

app/views/lookup_table_precios/new.html.erb
<h1>New lookup_table_precio</h1>

<%= render 'form' %>

<%= link_to 'Back', lookup_table_precios_path %>

app/views/lookup_table_precios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Producto:</b>
  <%= @lookup_table_precio.producto %>
</p>

<p>
  <b>Zona:</b>
  <%= @lookup_table_precio.zona %>
</p>

<p>
  <b>Edad:</b>
  <%= @lookup_table_precio.edad %>
</p>

<p>
  <b>Llave:</b>
  <%= @lookup_table_precio.llave %>
</p>

<p>
  <b>Pan_mx_i:</b>
  <%= @lookup_table_precio.pan_mx_i %>
</p>

<p>
  <b>Pan_mx_ii:</b>
  <%= @lookup_table_precio.pan_mx_ii %>
</p>

<p>
  <b>Pan_mx_iii:</b>
  <%= @lookup_table_precio.pan_mx_iii %>
</p>

<p>
  <b>Pan_mx_iv:</b>
  <%= @lookup_table_precio.pan_mx_iv %>
</p>

<p>
  <b>Pan_mx_v:</b>
  <%= @lookup_table_precio.pan_mx_v %>
</p>


<%= link_to 'Edit', edit_lookup_table_precio_path(@lookup_table_precio) %> |
<%= link_to 'Back', lookup_table_precios_path %>