config/routes.rb
Prospera2::Application.routes.draw do
  

  resources :aglayouts

  resources :lookup_table_precios

  resources :plans

  resources :layouts
  resources :temp_layouts
   get 'gracias' => 'home#thankyou'
   get 'palig' => 'home#palig'
   get 'bupa' => 'home#bupa'
   get 'gastosmedicos' => 'home#gastosmedicos'
   get 'cotizacionpalig' => 'home#cotizacionpalig'
   get 'agentes' => 'home#agentes'

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@layout = Layout.new


  end
  def agentes
    @layout = Aglayout.new


  end

  def cotizacionpalig
    @layout = Layout.last
    
    if @layout.formadepago == 'Anual'
      @formapago = 1
      @rpf = 0
      @formapagosubsecuentes = 0/@formapago
    elsif @layout.formadepago == 'Semestral'
       @formapago = 2
       @rpf = 0.045
       @formapagosubsecuentes = 0.5
    elsif @layout.formadepago == 'Trimestral'
       @formapago = 4
       @rpf = 0.075
       @formapagosubsecuentes = 0.25
    end
      
    @iva = 0.16
    @prod = @layout.plan
    if @prod == 'PA'
      @plan = Plan.where(nombre: 'Preferred Access').first
    elsif @prod == 'WA'
      @plan = Plan.where(nombre: 'World Access').first
    end
    
    case @layout.estadoderesidencia
    when "Aguascalientes"
      @zona = 5
    when "Baja California (Ensenada)"
      @zona = 1
    when "Baja California (Mexicalli)"
      @zona = 1
    when "Baja California (Playas de Rosarito)"
      @zona = 1
    when "Baja California (Rodolfo Sánchez T.  (Maneadero))"
      @zona = 1
    when "Baja California (San Felipe)"
      @zona = 1
    when "Baja California (Tecate)"
      @zona = 1
    when "Baja California (Tijuana)"
      @zona = 1
    when "Baja California (OTRAS CIUDADES)"
      @zona = 2
    when "Baja California Sur"
      @zona = 2
    when "Campeche"
      @zona = 6
    when "Chiapas"
      @zona = 6
    when "Chihuahua (Juárez)"
      @zona = 1
    when "Chihuahua (Manuel Ojinaga)"
      @zona = 1
    when "Chihuahua (OTRAS CIUDADES)"
      @zona = 3
    when "Coahuila (Ciudad Acuña)"
      @zona = 1
    when "Coahuila (Matamoros)"
      @zona = 1
    when "Coahuila (Piedras Negras)"
      @zona = 1
    when "Coahuila (OTRAS CIUDADES)"
      @zona = 3
    when "Colima"
      @zona = 4
    when "Distrito Federal(y área metropolitana)"
      @zona = 1
    when "Durango"
      @zona = 4
    when "Estado de México(excepto área metropolitana)"
      @zona = 3
    when "Guanajuato"
      @zona = 4
    when "Guerrero(Acapulco)"
      @zona = 4
    when "Guerrero(Zihuatanejo)"
      @zona = 4
    when "Guerrero(OTRAS CIUDADES)"
      @zona = 4
    when "Hidalgo"
      @zona = 3
    when "Jalisco"
      @zona = 3
    when "Michoacán"
      @zona = 6
    when "Morelos"
      @zona = 3
    when "Nayarit"
      @zona = 4
    when "Nuevo León (Anáhuac)"
      @zona = 1
    when "Nuevo León (OTRAS CIUDADES)"
      @zona = 2
    when "Oaxaca"
      @zona = 6
    when "Puebla"
      @zona = 3
    when "Querétaro"
      @zona = 4
    when "Quintana Roo"
      @zona = 4
    when "San Luis Potosí"
      @zona = 5
    when "Sinaloa"
      @zona = 4
    when "Sonora (Agua Prieta)"
      @zona = 1
    when "Sonora (Caborca)"
      @zona = 1
    when "Sonora (Ciudad de Cananea)"
      @zona = 1
    when "Sonora (Nogales)"
      @zona = 1
    when "Sonora (Puerto Peñasco)"
      @zona = 1
    when "Sonora (San Luis Río Colorado)"
      @zona = 1
    when "Sonora (Sonoita)"
      @zona = 1
    when "Sonora (OTRAS CIUDADES)"
      @zona = 2
    when "Tabasco"
      @zona = 6
    when "Tamaulipas (Ciudad Camargo)"
      @zona = 1
    when "Tamaulipas (Ciudad Gustavo Díaz Ordaz)"
      @zona = 1
    when "Tamaulipas (Ciudad Miguel Alemán)"
      @zona = 1
    when "Tamaulipas (Ciudad Río Bravo)"
      @zona = 1
    when "Tamaulipas (Nueva Ciudad Guerrero)"
      @zona = 1
    when "Tamaulipas (Nuevo Laredo)"
      @zona = 1
    when "Tamaulipas (Reynosa)"
      @zona = 1
    when "Tamaulipas (Valle Hermoso)"
      @zona = 1
    when "Tamaulipas (OTRAS CIUDADES)"
      @zona = 3
    when "Tlaxcala"
      @zona = 5
    when "Veracruz"
      @zona = 5
    when "Yucatán"
      @zona = 6
    when "Zacatecas" 
      @zona = 5
      
    else
      @zona = 0
    end

  
    @calculo_deducible1 = (((LookupTablePrecio.where(zona: @zona, edad: @layout.edadetitular, producto: @prod).first.pan_mx_i)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddeconyugue, producto: @prod).first.pan_mx_i)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddelamadredeltitular, producto: @prod).first.pan_mx_i)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddelasuegradeltitular, producto: @prod).first.pan_mx_i)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddelpadredeltitular, producto: @prod).first.pan_mx_i)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddelasuegrodeltitular, producto: @prod).first.pan_mx_i) + (LookupTablePrecio.where(zona: @zona, edad: @layout.edaddehijo1mayora24, producto: @prod).first.pan_mx_i)+ (LookupTablePrecio.where(zona: @zona, edad: @layout.edaddehijo2mayora24, producto: @prod).first.pan_mx_i)+ (LookupTablePrecio.where(zona: @zona, edad: @layout.edaddehijo4mayora24, producto: @prod).first.pan_mx_i)+ (LookupTablePrecio.where(zona: @zona, edad: @layout.edaddehijo1mayora24, producto: @prod).first.pan_mx_i)+ (LookupTablePrecio.where(zona: @zona, edad: @layout.numdehijosconedadde24ymenores, producto: @prod).first.pan_mx_i))*(1+@rpf)/(@formapago.to_f)+900)*(1+@iva)
    @calculo_deducible2 = (((LookupTablePrecio.where(zona: @zona, edad: @layout.edadetitular, producto: @prod).first.pan_mx_ii)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddeconyugue, producto: @prod).first.pan_mx_ii)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddelamadredeltitular, producto: @prod).first.pan_mx_ii)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddelasuegradeltitular, producto: @prod).first.pan_mx_ii)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddelpadredeltitular, producto: @prod).first.pan_mx_ii)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddelasuegrodeltitular, producto: @prod).first.pan_mx_ii) + (LookupTablePrecio.where(zona: @zona, edad: @layout.edaddehijo1mayora24, producto: @prod).first.pan_mx_ii)+ (LookupTablePrecio.where(zona: @zona, edad: @layout.edaddehijo2mayora24, producto: @prod).first.pan_mx_ii)+ (LookupTablePrecio.where(zona: @zona, edad: @layout.edaddehijo4mayora24, producto: @prod).first.pan_mx_ii)+ (LookupTablePrecio.where(zona: @zona, edad: @layout.edaddehijo1mayora24, producto: @prod).first.pan_mx_ii)+ (LookupTablePrecio.where(zona: @zona, edad: @layout.numdehijosconedadde24ymenores, producto: @prod).first.pan_mx_ii))*(1+@rpf)/(@formapago.to_f)+900)*(1+@iva)
    @calculo_deducible3 = (((LookupTablePrecio.where(zona: @zona, edad: @layout.edadetitular, producto: @prod).first.pan_mx_iii)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddeconyugue, producto: @prod).first.pan_mx_iii)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddelamadredeltitular, producto: @prod).first.pan_mx_iii)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddelasuegradeltitular, producto: @prod).first.pan_mx_iii)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddelpadredeltitular, producto: @prod).first.pan_mx_iii)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddelasuegrodeltitular, producto: @prod).first.pan_mx_iii) + (LookupTablePrecio.where(zona: @zona, edad: @layout.edaddehijo1mayora24, producto: @prod).first.pan_mx_iii)+ (LookupTablePrecio.where(zona: @zona, edad: @layout.edaddehijo2mayora24, producto: @prod).first.pan_mx_iii)+ (LookupTablePrecio.where(zona: @zona, edad: @layout.edaddehijo4mayora24, producto: @prod).first.pan_mx_iii)+ (LookupTablePrecio.where(zona: @zona, edad: @layout.edaddehijo1mayora24, producto: @prod).first.pan_mx_iii)+ (LookupTablePrecio.where(zona: @zona, edad: @layout.numdehijosconedadde24ymenores, producto: @prod).first.pan_mx_iii))*(1+@rpf)/(@formapago.to_f)+900)*(1+@iva)
    @calculo_deducible4 = (((LookupTablePrecio.where(zona: @zona, edad: @layout.edadetitular, producto: @prod).first.pan_mx_iv)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddeconyugue, producto: @prod).first.pan_mx_iv)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddelamadredeltitular, producto: @prod).first.pan_mx_iv)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddelasuegradeltitular, producto: @prod).first.pan_mx_iv)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddelpadredeltitular, producto: @prod).first.pan_mx_iv)+(LookupTablePrecio.where(zona: @zona, edad: @layout.edaddelasuegrodeltitular, producto: @prod).first.pan_mx_iv) + (LookupTablePrecio.where(zona: @zona, edad: @layout.edaddehijo1mayora24, producto: @prod).first.pan_mx_iv)+ (LookupTablePrecio.where(zona: @zona, edad: @layout.edaddehijo2mayora24, producto: @prod).first.pan_mx_iv)+ (LookupTablePrecio.where(zona: @zona, edad: @layout.edaddehijo4mayora24, producto: @prod).first.pan_mx_iv)+ (LookupTablePrecio.where(zona: @zona, edad: @layout.edaddehijo1mayora24, producto: @prod).first.pan_mx_iv)+ (LookupTablePrecio.where(zona: @zona, edad: @layout.numdehijosconedadde24ymenores, producto: @prod).first.pan_mx_iv))*(1+@rpf)/(@formapago.to_f)+900)*(1+@iva)

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/agentes.html.erb
<div class="headliner2">
  <h1 class="headlinertext2">REALIZA UNA COTIZACIÓN</h1>
</div>
<div class="form-main">


<%= simple_form_for @layout  do |f| %>
    <%=f.input :nombre, label: 'Nombre', :required => true %>
    <%=f.input :celular, label: 'Celular', :required => true %>
    <%=f.input :email, label: 'Email', :required => true %>
    <%= f.input :estadoderesidencia, label: 'Estado de Residencia', :collection => ["Aguascalientes",
"Baja California (Ensenada)",
"Baja California (Mexicalli)",
"Baja California (Playas de Rosarito)",
"Baja California (Rodolfo Sánchez T.  (Maneadero))",
"Baja California (San Felipe)",
"Baja California (Tecate)",
"Baja California (Tijuana)",
"Baja California (OTRAS CIUDADES)",
"Baja California Sur",
"Campeche",
"Chiapas",
"Chihuahua (Juárez)",
"Chihuahua (Manuel Ojinaga)",
"Chihuahua (OTRAS CIUDADES)",
"Coahuila (Ciudad Acuña)",
"Coahuila (Matamoros)",
"Coahuila (Piedras Negras)",
"Coahuila (OTRAS CIUDADES)",
"Colima",
"Distrito Federal(y área metropolitana)",
"Durango",
"Estado de México(excepto área metropolitana)",
"Guanajuato",
"Guerrero(Acapulco)",
"Guerrero(Zihuatanejo)",
"Guerrero(OTRAS CIUDADES)",
"Hidalgo",
"Jalisco",
"Michoacán",
"Morelos",
"Nayarit",
"Nuevo León (Anáhuac)",
"Nuevo León (OTRAS CIUDADES)",
"Oaxaca",
"Puebla",
"Querétaro",
"Quintana Roo",
"San Luis Potosí",
"Sinaloa",
"Sonora (Agua Prieta)",
"Sonora (Caborca)",
"Sonora (Ciudad de Cananea)",
"Sonora (Nogales)",
"Sonora (Puerto Peñasco)",
"Sonora (San Luis Río Colorado)",
"Sonora (Sonoita)",
"Sonora (OTRAS CIUDADES)",
"Tabasco",
"Tamaulipas (Ciudad Camargo)",
"Tamaulipas (Ciudad Gustavo Díaz Ordaz)",
"Tamaulipas (Ciudad Miguel Alemán)",
"Tamaulipas (Ciudad Río Bravo)",
"Tamaulipas (Nueva Ciudad Guerrero)",
"Tamaulipas (Nuevo Laredo)",
"Tamaulipas (Reynosa)",
"Tamaulipas (Valle Hermoso)",
"Tamaulipas (OTRAS CIUDADES)",
"Tlaxcala",
"Veracruz",
"Yucatán",
"Zacatecas"], :required => true%>


    <%= f.input :edadetitular, label: 'Edad del titular', :collection =>(18..99), :required => true%> 
    <%=f.input :edaddeconyugue, label: 'Edad de conyugue', :collection =>(18..99)%>
    <%=f.input :numdehijosconedadde24ymenores, label: 'Numero de hijos con edad de 24 y menores', :collection =>(0..8)%> 
    <%=f.input :formadepago, label: 'Forma de Pago', :collection =>["Anual","Semestral","Trimestral"], :required => true%> 
    <%=f.input :edaddehijo1mayora24, label: 'Edad de hijo 1 mayor a 24', :collection =>(25..99)%> 
    <%=f.input :edaddehijo2mayora24, label: 'Edad de hijo 2 mayor a 24', :collection =>(25..99)%> 
    <%=f.input :edaddehijo3mayora24, label: 'Edad de hijo 3 mayor a 24', :collection =>(25..99)%> 
    <%=f.input :edaddehijo4mayora24, label: 'Edad de hijo 4 mayor a 24', :collection =>(25..99)%> 
    <%=f.input :edaddelpadredeltitular, label: 'Edad del padre del titular', :collection =>(25..99)%> 
    <%=f.input :edaddelamadredeltitular, label: 'Edad de la madre del titular', :collection =>(25..99)%> 
    <%=f.input :edaddelasuegradeltitular, label: 'Edad de la suegra del titular', :collection =>(25..99)%> 
    <%=f.input :edaddelasuegrodeltitular , label: 'Edad del suegro del titular', :collection =>(25..99)%>
    <%=f.input :viajes, label: '¿Cuántos viajes fuera de México realiza al año?', :collection => ['0','1','2','3', '4 o más'], :required => true%>
    <%=f.input :cashemergencia, label: 'En caso de una emergencia médica, ¿con cuánto dinero dispone al momento del incidente? ', :collection => ['$10,000 - $30,000 MXN', '$50,000 - $75,000 MXN', '$100,000 MXN o más' ], :required => true %>

	
	<%= f.button :submit, "Enviar" %>
<% end %>
</div>

app/views/home/cotizacionpalig.html.erb
<h1>COTIZACIÓN DE SEGURO DE GASTOS MÉDICOS INTERNACIONAL INDIVIDUAL / FAMILIAR	</h1>
<p>Solicitante: <%=@layout.nombre%></p>
<p>Edad del Solicitante: <%=@layout.edadetitular%></p>
<p>No. dependientes: </p>
<p>Edad del Cónyugue: <%=@layout.edaddeconyugue%></p>
<p>Edad de la Madre del  Titular: <%=@layout.edaddelamadredeltitular%></p>
<p>Edad de la Suegra del  Titular: <%=@layout.edaddelasuegradeltitular%></p>
<p>Edad del Padre del  Titular: <%=@layout.edaddelpadredeltitular%></p>
<p>Edad del Suegro del  Titular: <%=@layout.edaddelasuegrodeltitular%></p>
<p>No. Hijos MENORES de 24* años: <%=@layout.numdehijosconedadde24ymenores%></p>
<p> Edad del Hijo 1 MAYOR de 24 años: <%=@layout.edaddehijo1mayora24%></p>
<p> Edad del Hijo 2 MAYOR de 24 años: <%=@layout.edaddehijo2mayora24%></p>
<p> Edad del Hijo 3 MAYOR de 24 años: <%=@layout.edaddehijo3mayora24%></p>
<p> Edad del Hijo 4 MAYOR de 24 años: <%=@layout.edaddehijo4mayora24%></p>
<p> Estado de Residencia: <%=@layout.estadoderesidencia%></p>
<p>Producto: <%=@plan.nombre %></p>
<p>Forma de Pago: <%=@layout.formadepago %></p>
<p>Zona de Emisión: <%=@zona %> </p>


<table>
    <tr><th>Deducible</th><th>Primer Pago(1,2)</th><th>Subsecuentes(2)</th><th>Total al cobro</th></tr>
    <% if @layout.cashemergencia ==  '$10,000 - $30,000 MXN' %>
     <tr><td>USD 2,000</td><td><%= number_to_currency @calculo_deducible2%></td><td><%=number_to_currency @subsecuentes2%></td><td><%= number_to_currency @calculo_total2%></td></tr>
	<% elsif @layout.cashemergencia ==  '$50,000 - $75,000 MXN' %>
	<tr><td>USD 5,000</td><td><%= number_to_currency @calculo_deducible3%></td><td><%=number_to_currency @subsecuentes3%></td><td><%= number_to_currency @calculo_total3%></td></tr>
	<% elsif @layout.cashemergencia ==  '$100,000 MXN o más'%>
	<tr><td>USD 10,000</td><td><%= number_to_currency @calculo_deducible4%></td><td><%=number_to_currency @subsecuentes4%></td><td><%= number_to_currency @calculo_total4%></td></tr>
	<% end %> 
    
</table>

<p>(*) Conforme a Condiciones Generales de Póliza.</p>
<p>(1) Nota: Ya incluye Derecho de Póliza e IVA.</p>
<p>(2) Nota: En su caso se incluye Recargo Pago Fraccionado.</p>

<h2 align="center">***<%= @plan.nombre %>***</h2>
<div class="box">
	<p>Cobertura Máxima Anual por Asegurado: <%= @plan.cobertura_maxima_anual_asegurado%></p>
	<p>Área de Cobertura: <%= @plan.area_cobertura%></p>
	<p>Deducible: <%= @plan.deducible%></p>
	<h3 align="center">BENEFICIOS EXCLUSIVOS DE PAN-AMERICAN</h3>
	<p>Reducción del deducible al 50%: <%= @plan.reduc_deducible%></p>
	<p>Eliminación de deducible en caso de accidente: <%= @plan.elim_deducible%></p>
	<h3 align="center">PRINCIPALES BENEFICIOS</h3>
	<p>Hospitalización, Habitación, alojamiento y Unidad de Cuidados Intensivos: <%= @plan.hospitalizacion%></p>
	<p>Honorarios Médicos: <%= @plan.honorarios_medicos %></p>
	<p>Estudios de laboratorio, patología y diagnóstico por imágenes: <%= @plan.estudios_laboratorio%></p>
	<p>Acompañante de un asegurado hospitalizado (por noche): <%= @plan.acompanante_noche%></p>
	<p>Maternidad normal y cuidados del Recién Nacido (Por evento). Sólo cubiertas en Planes I y II: <%= @plan.maternidad%></p>
	<p>Complicaciones del embarazo y cuidados del recién nacido enfermo (De por vida). Sólo cubiertas en Planes I y II:	<%= @plan.complicaciones_embarazo%></p>
	<p>Trasplante de órganos: <%= @plan.trasplante_organos%></p>
	<p>Medicamentos ambulatorios recetados: <%= @plan.medicamentos%></p>
	<p>Ambulancia Aérea y Terrestre: <%= @plan.ambulancia %></p>
	<p>Exámenes médicos sin patología previa: <%= @plan.examenes_sin_patologia%></p>
	<p>Terapias complementarias. Quiropráctico, Psiquiatra o Psicólogo. (20 sesiones por año): <%= @plan.terapias%></p>
	<p>Tratamientos de podología: <%= @plan.podologia%></p>
	<p>Extensión de las coberturas: <%= @plan.extension_coberturas%></p>
	<br/>
</div>
<p>* Este cuadro muestra solamente un resumen de beneficios, para mayor detalle sobre las coberturas del producto por favor consulte las Condiciones Generales.</p>
<p>** Esta cotización es de carácter informativo y está sujeta a cambio a discreción de la compañía.</p>
<p>*** Cotizaciones para las personas de 76 años en adelante solo aplica para renovaciones.</p>
<p>**** Las primas están expresadas en moneda nacional y los beneficios así como deducibles en Dólares Americanos.</p>

<p><strong>Este documento solo constituye una cotización de seguro, por lo tanto, no representa garantía alguna de que la misma será aceptada por la compañía, ni de que en caso de aceptarse, la aceptación concuerde totalmente con los términos de la misma, ya que es tentativa y sujeta a la evaluación correspondiente por parte de nuestros suscriptores. Además esta condicionada a la presentación de los requisitos de suscripción indicados en su oportunidad, así como al resultado de las evaluaciones necesarias. La Compañía se reserva el derecho de aceptación o declinación del riesgo propuesto.  </strong></p>
<br/>
<br/>

app/views/home/thankyou.html.erb
<!-- Google Code for Veseguro | Individual Mexican Buyer Conversions Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 965861289;
var google_conversion_language = "es";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "sgV5CJ7WolcQqb_HzAM";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/965861289/?label=sgV5CJ7WolcQqb_HzAM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

<style type="text/css">
	body {
	background-color: #ecf0f1;
	border-color: #bdc3c7;
	width: 100%;
	
}


.ph3 {
  font-size: 30px;
  font-weight: normal;
  color: #2c3e50;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  text-align: center;
  margin-bottom: 43px;
  font-weight: 300;
  
}
.pthankyou {
  font-size: 16px;
  font-weight: normal;
  color: #7f8c8d;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  line-height: 29.6px;
  text-align: center;

}
</style>

<div class="page-wrapper"><section class="bg-clouds">
<div class="thankyouicon"></div>

                    <h3 class="ph3">La información fue procesada exitosamente</h3>

                <p class="pthankyou">Haz click en la cotización a checar
                </p>
<div style="text-align:center;">
  <%= link_to 'Checar cotización PALIG', palig_path %><br>
  <%= link_to 'Checar cotización BUPA', bupa_path %>
  
</div>