config/routes.rb
Prospera2::Application.routes.draw do
  

  resources :aglayouts

  resources :lookup_table_precios

  resources :plans

  resources :layouts
  resources :temp_layouts
   get 'gracias' => 'home#thankyou'
   get 'palig' => 'home#palig'
   get 'bupa' => 'home#bupa'
   get 'gastosmedicos' => 'home#gastosmedicos'
   get 'cotizacionpalig' => 'home#cotizacionpalig'
   get 'agentes' => 'home#agentes'

  root :to => 'home#index'

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  attr_accessible :acompanante_noche, :ambulancia, :area_cobertura, :cobertura_maxima_anual_asegurado, :complicaciones_embarazo, :deducible, :elim_deducible, :estudios_laboratorio, :examenes_sin_patologia, :extension_coberturas, :honorarios_medicos, :hospitalizacion, :maternidad, :medicamentos, :nombre, :podologia, :reduc_deducible, :terapias, :trasplante_organos
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @plans }
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @plan = Plan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/new
  # GET /plans/new.json
  def new
    @plan = Plan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/1/edit
  def edit
    @plan = Plan.find(params[:id])
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(params[:plan])

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render json: @plan, status: :created, location: @plan }
      else
        format.html { render action: "new" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /plans/1
  # PUT /plans/1.json
  def update
    @plan = Plan.find(params[:id])

    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cobertura_maxima_anual_asegurado %><br />
    <%= f.text_field :cobertura_maxima_anual_asegurado %>
  </div>
  <div class="field">
    <%= f.label :area_cobertura %><br />
    <%= f.text_field :area_cobertura %>
  </div>
  <div class="field">
    <%= f.label :deducible %><br />
    <%= f.text_field :deducible %>
  </div>
  <div class="field">
    <%= f.label :reduc_deducible %><br />
    <%= f.text_field :reduc_deducible %>
  </div>
  <div class="field">
    <%= f.label :elim_deducible %><br />
    <%= f.text_field :elim_deducible %>
  </div>
  <div class="field">
    <%= f.label :hospitalizacion %><br />
    <%= f.text_field :hospitalizacion %>
  </div>
  <div class="field">
    <%= f.label :honorarios_medicos %><br />
    <%= f.text_field :honorarios_medicos %>
  </div>
  <div class="field">
    <%= f.label :estudios_laboratorio %><br />
    <%= f.text_field :estudios_laboratorio %>
  </div>
  <div class="field">
    <%= f.label :acompanante_noche %><br />
    <%= f.text_field :acompanante_noche %>
  </div>
  <div class="field">
    <%= f.label :maternidad %><br />
    <%= f.text_field :maternidad %>
  </div>
  <div class="field">
    <%= f.label :complicaciones_embarazo %><br />
    <%= f.text_field :complicaciones_embarazo %>
  </div>
  <div class="field">
    <%= f.label :trasplante_organos %><br />
    <%= f.text_field :trasplante_organos %>
  </div>
  <div class="field">
    <%= f.label :medicamentos %><br />
    <%= f.text_field :medicamentos %>
  </div>
  <div class="field">
    <%= f.label :ambulancia %><br />
    <%= f.text_field :ambulancia %>
  </div>
  <div class="field">
    <%= f.label :examenes_sin_patologia %><br />
    <%= f.text_field :examenes_sin_patologia %>
  </div>
  <div class="field">
    <%= f.label :terapias %><br />
    <%= f.text_field :terapias %>
  </div>
  <div class="field">
    <%= f.label :podologia %><br />
    <%= f.text_field :podologia %>
  </div>
  <div class="field">
    <%= f.label :extension_coberturas %><br />
    <%= f.text_field :extension_coberturas %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<h1>Listing plans</h1>

<table>
  <tr>
    <th>Cobertura maxima anual asegurado</th>
    <th>Area cobertura</th>
    <th>Deducible</th>
    <th>Reduc deducible</th>
    <th>Elim deducible</th>
    <th>Hospitalizacion</th>
    <th>Honorarios medicos</th>
    <th>Estudios laboratorio</th>
    <th>Acompanante noche</th>
    <th>Maternidad</th>
    <th>Complicaciones embarazo</th>
    <th>Trasplante organos</th>
    <th>Medicamentos</th>
    <th>Ambulancia</th>
    <th>Examenes sin patologia</th>
    <th>Terapias</th>
    <th>Podologia</th>
    <th>Extension coberturas</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @plans.each do |plan| %>
  <tr>
    <td><%= plan.cobertura_maxima_anual_asegurado %></td>
    <td><%= plan.area_cobertura %></td>
    <td><%= plan.deducible %></td>
    <td><%= plan.reduc_deducible %></td>
    <td><%= plan.elim_deducible %></td>
    <td><%= plan.hospitalizacion %></td>
    <td><%= plan.honorarios_medicos %></td>
    <td><%= plan.estudios_laboratorio %></td>
    <td><%= plan.acompanante_noche %></td>
    <td><%= plan.maternidad %></td>
    <td><%= plan.complicaciones_embarazo %></td>
    <td><%= plan.trasplante_organos %></td>
    <td><%= plan.medicamentos %></td>
    <td><%= plan.ambulancia %></td>
    <td><%= plan.examenes_sin_patologia %></td>
    <td><%= plan.terapias %></td>
    <td><%= plan.podologia %></td>
    <td><%= plan.extension_coberturas %></td>
    <td><%= link_to 'Show', plan %></td>
    <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
    <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cobertura maxima anual asegurado:</b>
  <%= @plan.cobertura_maxima_anual_asegurado %>
</p>

<p>
  <b>Area cobertura:</b>
  <%= @plan.area_cobertura %>
</p>

<p>
  <b>Deducible:</b>
  <%= @plan.deducible %>
</p>

<p>
  <b>Reduc deducible:</b>
  <%= @plan.reduc_deducible %>
</p>

<p>
  <b>Elim deducible:</b>
  <%= @plan.elim_deducible %>
</p>

<p>
  <b>Hospitalizacion:</b>
  <%= @plan.hospitalizacion %>
</p>

<p>
  <b>Honorarios medicos:</b>
  <%= @plan.honorarios_medicos %>
</p>

<p>
  <b>Estudios laboratorio:</b>
  <%= @plan.estudios_laboratorio %>
</p>

<p>
  <b>Acompanante noche:</b>
  <%= @plan.acompanante_noche %>
</p>

<p>
  <b>Maternidad:</b>
  <%= @plan.maternidad %>
</p>

<p>
  <b>Complicaciones embarazo:</b>
  <%= @plan.complicaciones_embarazo %>
</p>

<p>
  <b>Trasplante organos:</b>
  <%= @plan.trasplante_organos %>
</p>

<p>
  <b>Medicamentos:</b>
  <%= @plan.medicamentos %>
</p>

<p>
  <b>Ambulancia:</b>
  <%= @plan.ambulancia %>
</p>

<p>
  <b>Examenes sin patologia:</b>
  <%= @plan.examenes_sin_patologia %>
</p>

<p>
  <b>Terapias:</b>
  <%= @plan.terapias %>
</p>

<p>
  <b>Podologia:</b>
  <%= @plan.podologia %>
</p>

<p>
  <b>Extension coberturas:</b>
  <%= @plan.extension_coberturas %>
</p>


<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>